name: konsi_test
description: "A Challenge from Konsi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3 

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  connectivity_plus: ^6.0.5
  custom_refresh_indicator: ^4.0.1
  easy_mask: ^2.0.1
  equatable: ^2.0.5
  flextras: ^1.0.0
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_modular: ^6.3.4
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  googlemaps_flutter_webservices: ^1.0.2
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  sqflite: ^2.3.3+1
  toastification: ^2.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false

  image_path: "assets/logo/android.png"
  adaptive_icon_foreground: "assets/logo/android.png"
  adaptive_icon_background: "#2E8896"

flutter_native_splash:
  android: true
  ios: false
  web: false
  
  color: "#2E8896"
  image: assets/native_splash.png

  android_12:
    color: "#2E8896"
    image: assets/native_splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/lottie/
    - assets/svgs/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
          
  